"""Generates the dot-grid world map used by the Users-by-Country panel.

A real vector world map is a 200KB path nobody needs at this size. A dot grid
reads as a world map at a glance, is forgiving about a few degrees of error,
and lets individual countries be lit up by giving their dots a class.

    python scripts/build_map.py

Land is approximated by coarse lat/lon polygons below. They are deliberately
rough — this is a decorative locator, not a basemap.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Equirectangular grid. Columns span -180..180, rows span 83..-56 (Antarctica
# is left off; it is never the answer to "where are my users").
COLS, ROWS = 62, 26
LON0, LON1 = -170.0, 185.0
LAT0, LAT1 = 78.0, -55.0

DOT_R = 2.6
STEP_X = 9.2
STEP_Y = 9.2
PAD = 4

# (name, [(lon, lat), ...]) — clockwise-ish, closed implicitly.
LAND = [
    ("greenland", [(-58, 82), (-20, 82), (-18, 70), (-42, 60), (-55, 65), (-72, 76)]),
    ("north_america", [
        (-168, 66), (-142, 70), (-120, 72), (-95, 74), (-80, 73), (-62, 60),
        (-55, 47), (-66, 44), (-75, 35), (-81, 25), (-97, 26), (-104, 29),
        (-117, 32), (-125, 40), (-131, 52), (-141, 60), (-160, 60),
    ]),
    ("central_america", [
        (-105, 22), (-88, 21), (-77, 8), (-82, 7), (-92, 14), (-99, 16),
    ]),
    ("south_america", [
        (-79, 9), (-60, 12), (-50, 0), (-35, -6), (-38, -22), (-48, -34),
        (-58, -40), (-65, -55), (-74, -50), (-72, -30), (-70, -18), (-81, -5),
    ]),
    ("europe", [
        (-10, 44), (-2, 51), (4, 53), (8, 58), (12, 66), (26, 71), (32, 66),
        (40, 60), (40, 48), (28, 41), (20, 40), (8, 44), (0, 41), (-9, 38),
    ]),
    ("uk", [(-8, 50), (2, 53), (0, 59), (-6, 58), (-11, 54)]),
    ("africa", [
        (-17, 21), (-6, 36), (11, 37), (24, 32), (34, 31), (43, 12), (51, 12),
        (42, -2), (40, -16), (35, -25), (26, -34), (18, -35), (12, -18),
        (8, -1), (9, 5), (-8, 5), (-17, 14),
    ]),
    ("middle_east", [(34, 37), (48, 40), (60, 38), (58, 24), (44, 12), (35, 28)]),
    ("asia", [
        (40, 75), (70, 78), (105, 78), (140, 73), (160, 70), (172, 65),
        (155, 55), (140, 50), (130, 43), (122, 32), (118, 22), (105, 10),
        (98, 8), (92, 21), (78, 8), (70, 22), (62, 25), (55, 38), (48, 44),
        (42, 50), (40, 62),
    ]),
    ("japan", [(130, 31), (141, 36), (146, 44), (140, 45), (132, 34)]),
    ("indonesia", [(95, 6), (120, 2), (141, -2), (140, -9), (118, -9), (100, -3)]),
    ("philippines", [(119, 18), (126, 17), (127, 6), (121, 5)]),
    ("australia", [
        (114, -22), (122, -17), (132, -11), (142, -11), (150, -22), (153, -28),
        (146, -39), (135, -35), (126, -32), (115, -34),
    ]),
    ("new_zealand", [(166, -45), (174, -35), (178, -38), (172, -47)]),
    ("madagascar", [(43, -12), (50, -16), (47, -25), (44, -20)]),
]

# Countries the panel lists, as the grid cells to light up. Given as
# (lon, lat) seeds with a radius in cells, which is easier to keep right than
# picking grid indices by hand.
LIT = {
    "CA": [(-106, 56), 3.4],
    "US": [(-98, 39), 3.0],
    "GB": [(-2, 54), 1.0],
    "IN": [(79, 22), 1.8],
    "AU": [(134, -25), 3.0],
}


def inside(poly, x, y):
    """Even-odd point in polygon."""
    n, hit = len(poly), False
    for i in range(n):
        x1, y1 = poly[i]
        x2, y2 = poly[(i + 1) % n]
        if (y1 > y) != (y2 > y):
            xx = x1 + (y - y1) / (y2 - y1) * (x2 - x1)
            if x < xx:
                hit = not hit
    return hit


def main() -> int:
    w = PAD * 2 + (COLS - 1) * STEP_X
    h = PAD * 2 + (ROWS - 1) * STEP_Y
    out = [
        "{# Generated by scripts/build_map.py - do not hand-edit. #}",
        f'<svg class="map" viewBox="0 0 {w:.0f} {h:.0f}" role="img"'
        ' aria-label="World map with the top five countries highlighted">',
    ]

    for r in range(ROWS):
        lat = LAT0 + (LAT1 - LAT0) * (r / (ROWS - 1))
        for c in range(COLS):
            lon = LON0 + (LON1 - LON0) * (c / (COLS - 1))
            lon_w = ((lon + 180) % 360) - 180          # wrap the Pacific seam
            if not any(inside(p, lon_w, lat) for _n, p in LAND):
                continue

            cls = ""
            for _code, (seed, rad) in LIT.items():
                dx = (lon_w - seed[0]) / ((LON1 - LON0) / (COLS - 1))
                dy = (lat - seed[1]) / ((LAT1 - LAT0) / (ROWS - 1))
                if (dx * dx + dy * dy) ** 0.5 <= rad:
                    cls = ' class="lit"'
                    break

            x = PAD + c * STEP_X
            y = PAD + r * STEP_Y
            out.append(f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="{DOT_R}"{cls}/>')

    out.append("</svg>")
    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
